theory Top1
  imports Complex_Main
begin

(*
  Formalization stubs (statements only, no proofs) for /mnt/data/top1.tex

  Notes:
  - This file is intended to mirror the mathematical content of top1.tex
    (Munkres, Chapter 2, §§12–17) at the level of definitions and stated results.
  - Proofs are omitted using 'sorry' (no axioms).
*)

section \<open>\<S>12 Topological Spaces\<close>

(** from \S12 Definition (Topology on a set) [top1.tex:49] **)
(** LATEX VERSION: "A topology on a set X is a collection T of subsets of X ..." **)
definition is_topology_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_topology_on X T \<longleftrightarrow>
     {} \<in> T \<and> X \<in> T \<and>
     (\<forall>U. U \<subseteq> T \<longrightarrow> (\<Union>U) \<in> T) \<and>
     (\<forall>F. finite F \<and> F \<subseteq> T \<longrightarrow> (\<Inter>F) \<in> T)"

(** from \S12 (Open set terminology) [top1.tex:~55] **)
(** LATEX VERSION: "U is open in X iff U \<in> T." **)
definition openin_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "openin_on X T U \<longleftrightarrow> U \<in> T"

(** from \S12 Definition (Finer/coarser/comparable) [top1.tex:96] **)
(** LATEX VERSION: "T' is finer than T iff T \<subseteq> T' ..." **)
definition finer_than :: "'a set set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "finer_than T T' \<longleftrightarrow> T \<subseteq> T'"

definition strictly_finer_than :: "'a set set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "strictly_finer_than T T' \<longleftrightarrow> T \<subseteq> T' \<and> T \<noteq> T'"

definition comparable_topologies :: "'a set set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "comparable_topologies T T' \<longleftrightarrow> (T \<subseteq> T' \<or> T' \<subseteq> T)"


section \<open>\<S>13 Basis for a Topology\<close>

(** from \S13 Definition (Basis for a topology) [top1.tex:109] **)
(** LATEX VERSION: "B is a basis on X if (1) covers X and (2) intersection condition..." **)
definition is_basis_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_basis_on X B \<longleftrightarrow>
     (\<forall>x\<in>X. \<exists>b\<in>B. x \<in> b) \<and>
     (\<forall>b1\<in>B. \<forall>b2\<in>B. \<forall>x\<in>(b1 \<inter> b2).
         \<exists>b3\<in>B. x \<in> b3 \<and> b3 \<subseteq> (b1 \<inter> b2))"

(** from \S13 Definition (Topology generated by a basis) [top1.tex:109] **)
(** LATEX VERSION: "U is open iff for each x\<in>U there is basis element B with x\<in>B\<subseteq>U." **)
definition topology_generated_by_basis :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set set" where
  "topology_generated_by_basis X B =
     {U. U \<subseteq> X \<and> (\<forall>x\<in>U. \<exists>b\<in>B. x \<in> b \<and> b \<subseteq> U)}"

(** Convenience: "B is a basis for T on X" [implicit throughout \S13] **)
definition basis_for :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "basis_for X B T \<longleftrightarrow> is_basis_on X B \<and> T = topology_generated_by_basis X B"

(** from \S13 Lemma 13.1 [top1.tex:168] **)
(** LATEX VERSION: "T equals the collection of all unions of elements of B." **)
theorem Lemma_13_1:
  assumes "basis_for X B T"
  shows "T = { \<Union>U | U. U \<subseteq> B }"
  sorry

(** from \S13 Lemma 13.2 [top1.tex:176] **)
(** LATEX VERSION: "If C is a collection of open sets with local refinement property, then C is a basis." **)
theorem Lemma_13_2:
  assumes "is_topology_on X T"
  assumes "\<And>U x. U \<in> T \<Longrightarrow> x \<in> U \<Longrightarrow> \<exists>C\<in>Cc. C \<in> T \<and> x \<in> C \<and> C \<subseteq> U"
  shows "basis_for X Cc T"
  sorry

(** from \S13 Lemma 13.3 [top1.tex:184] **)
(** LATEX VERSION: "Criterion for T' finer than T in terms of bases." **)
theorem Lemma_13_3:
  assumes "basis_for X B T"
  assumes "basis_for X B' T'"
  shows "finer_than T T' \<longleftrightarrow>
    (\<forall>x\<in>X. \<forall>b\<in>B. x \<in> b \<longrightarrow> (\<exists>b'\<in>B'. x \<in> b' \<and> b' \<subseteq> b))"
  sorry


subsection \<open>Standard, lower limit, and K-topologies on \<real>\<close>

(** from \S13 Definition (standard, lower limit, K-topology) [top1.tex:205] **)
(** LATEX VERSION: "standard basis (a,b); lower limit basis [a,b); K basis (a,b) and (a,b)-K." **)

definition interval_open :: "real \<Rightarrow> real \<Rightarrow> real set" where
  "interval_open a b = {x. a < x \<and> x < b}"

definition interval_half_open_left_closed :: "real \<Rightarrow> real \<Rightarrow> real set" where
  "interval_half_open_left_closed a b = {x. a \<le> x \<and> x < b}"

definition K_set :: "real set" where
  "K_set = {x. \<exists>n::nat. n > 0 \<and> x = 1 / real n}"

definition basis_standard_R :: "real set set" where
  "basis_standard_R = { interval_open a b | a b. a < b }"

definition basis_lower_limit_R :: "real set set" where
  "basis_lower_limit_R = { interval_half_open_left_closed a b | a b. a < b }"

definition basis_K_topology_R :: "real set set" where
  "basis_K_topology_R =
     ({ interval_open a b | a b. a < b } \<union>
      { interval_open a b - K_set | a b. a < b })"

definition topology_standard_R :: "real set set" where
  "topology_standard_R = topology_generated_by_basis UNIV basis_standard_R"

definition topology_lower_limit_R :: "real set set" where
  "topology_lower_limit_R = topology_generated_by_basis UNIV basis_lower_limit_R"

definition topology_K_R :: "real set set" where
  "topology_K_R = topology_generated_by_basis UNIV basis_K_topology_R"

(** from \S13 Lemma 13.4 [top1.tex:221] **)
(** LATEX VERSION: "R_l and R_K are strictly finer than standard, but not comparable." **)
theorem Lemma_13_4:
  shows "strictly_finer_than topology_standard_R topology_lower_limit_R
       \<and> strictly_finer_than topology_standard_R topology_K_R
       \<and> \<not> comparable_topologies topology_lower_limit_R topology_K_R"
  sorry


subsection \<open>Subbasis\<close>

(** from \S13 Definition (Subbasis and generated topology) [top1.tex:231] **)
(** LATEX VERSION: "S subbasis: \<Union>S = X; topology is unions of finite intersections of S." **)
definition is_subbasis_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_subbasis_on X S \<longleftrightarrow> (\<Union>S = X)"

definition finite_intersections :: "'a set set \<Rightarrow> 'a set set" where
  "finite_intersections S =
     { \<Inter>F | F. finite F \<and> F \<subseteq> S }"

definition topology_generated_by_subbasis :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set set" where
  "topology_generated_by_subbasis X S =
     { \<Union>U | U. U \<subseteq> finite_intersections S }"


section \<open>\<S>14 The Order Topology\<close>

(** from \S14 Definition (Order topology on a simply ordered set) [top1.tex:314] **)
(** LATEX VERSION: "Order topology generated by open intervals and rays." **)

definition open_ray_gt :: "'a::linorder \<Rightarrow> 'a set" where
  "open_ray_gt a = {x. a < x}"

definition open_ray_lt :: "'a::linorder \<Rightarrow> 'a set" where
  "open_ray_lt a = {x. x < a}"

definition open_interval :: "'a::linorder \<Rightarrow> 'a \<Rightarrow> 'a set" where
  "open_interval a b = {x. a < x \<and> x < b}"

definition basis_order_topology :: "'a::linorder set set" where
  "basis_order_topology =
     ({ open_interval a b | a b. a < b } \<union>
      { open_ray_gt a | a. True } \<union>
      { open_ray_lt a | a. True })"

definition order_topology_on_UNIV :: "'a::linorder set set" where
  "order_topology_on_UNIV = topology_generated_by_basis UNIV basis_order_topology"

(** from \S14 Definition (Four interval types determined by a and b) [top1.tex:345] **)
(** LATEX VERSION: "If X ordered and a element, there are four intervals ..." **)
definition interval_types_four :: "'a::linorder \<Rightarrow> 'a \<Rightarrow> 'a set list" where
  "interval_types_four a b =
     [ {x. a < x \<and> x < b},
       {x. a \<le> x \<and> x < b},
       {x. a < x \<and> x \<le> b},
       {x. a \<le> x \<and> x \<le> b} ]"


section \<open>\<S>15 The Product Topology on X \<times> Y\<close>

(** from \S15 Definition (Product topology) [top1.tex:365] **)
(** LATEX VERSION: "Product topology generated by basis {U\<times>V | U open in X, V open in Y}." **)

definition product_basis :: "'a set set \<Rightarrow> 'b set set \<Rightarrow> ('a \<times> 'b) set set" where
  "product_basis TX TY =
     { U \<times> V | U V. U \<in> TX \<and> V \<in> TY }"

definition product_topology_on :: "'a set set \<Rightarrow> 'b set set \<Rightarrow> ('a \<times> 'b) set set" where
  "product_topology_on TX TY =
     topology_generated_by_basis UNIV (product_basis TX TY)"

(** from \S15 Definition (Projections) [top1.tex:401] **)
(** LATEX VERSION: "\<pi>1(x,y)=x, \<pi>2(x,y)=y." **)
definition pi1 :: "'a \<times> 'b \<Rightarrow> 'a" where "pi1 p = fst p"
definition pi2 :: "'a \<times> 'b \<Rightarrow> 'b" where "pi2 p = snd p"

definition preimage :: "('a \<Rightarrow> 'b) \<Rightarrow> 'b set \<Rightarrow> 'a set" where
  "preimage f U = {x. f x \<in> U}"

(** from \S15 Theorem 15.1 [top1.tex:379] **)
(** LATEX VERSION: "If B,C bases for X,Y then {B\<times>C} is a basis for X\<times>Y." **)
theorem Theorem_15_1:
  assumes "basis_for UNIV BX TX"
  assumes "basis_for UNIV BY TY"
  defines "D \<equiv> {B \<times> C | B C. B \<in> BX \<and> C \<in> BY}"
  shows "basis_for UNIV D (product_topology_on TX TY)"
  sorry

(** from \S15 Theorem 15.2 [top1.tex:425] **)
(** LATEX VERSION: "Subbasis for product topology: preimages of opens under projections." **)
theorem Theorem_15_2:
  assumes "is_topology_on UNIV TX"
  assumes "is_topology_on UNIV TY"
  defines "S \<equiv> { preimage pi1 U | U. U \<in> TX } \<union> { preimage pi2 V | V. V \<in> TY }"
  shows "product_topology_on TX TY = topology_generated_by_subbasis UNIV S"
  sorry


section \<open>\<S>16 The Subspace Topology\<close>

(** from \S16 Definition (Subspace topology) [top1.tex:450] **)
(** LATEX VERSION: "T_Y = {Y \<inter> U | U \<in> T}." **)
definition subspace_topology :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> 'a set set" where
  "subspace_topology X T Y = {Y \<inter> U | U. U \<in> T}"

(** from \S16 Lemma 16.1 [top1.tex:473] **)
(** LATEX VERSION: "If B is a basis for X, then {B\<inter>Y} is a basis for subspace topology on Y." **)
theorem Lemma_16_1:
  fixes Y :: "'a set"
  assumes "basis_for X B T"
  defines "BY \<equiv> {b \<inter> Y | b. b \<in> B}"
  shows "basis_for Y BY (subspace_topology X T Y)"
  sorry

(** from \S16 Lemma 16.2 [top1.tex:486] **)
(** LATEX VERSION: "If U open in Y and Y open in X, then U open in X." **)
theorem Lemma_16_2:
  assumes "is_topology_on X T"
  assumes "Y \<in> T"  (* Y open in X *)
  assumes "U \<in> subspace_topology X T Y"
  shows "U \<in> T"
proof -
  from assms(3) obtain V where hV: "V \<in> T" and hU: "U = Y \<inter> V"
    unfolding subspace_topology_def by blast
  from assms(1) have inter_T: "\<forall>F. finite F \<and> F \<subseteq> T \<longrightarrow> \<Inter>F \<in> T"
    unfolding is_topology_on_def by blast
  have fin: "finite {Y, V}" by simp
  have sub: "{Y, V} \<subseteq> T" using assms(2) hV by simp
  have "\<Inter>{Y, V} \<in> T" using inter_T fin sub by blast
  moreover have "\<Inter>{Y, V} = Y \<inter> V" by simp
  ultimately show "U \<in> T" using hU by simp
qed

(** from \S16 Theorem 16.3 [top1.tex:492] **)
(** LATEX VERSION: "Product topology on A\<times>B equals subspace topology from X\<times>Y." **)
theorem Theorem_16_3:
  assumes "is_topology_on X TX"
  assumes "is_topology_on Y TY"
  shows "product_topology_on (subspace_topology X TX A) (subspace_topology Y TY B)
       = subspace_topology (X \<times> Y) (product_topology_on TX TY) (A \<times> B)"
  sorry

(** from \S16 Theorem 16.4 [top1.tex:544] **)
(** LATEX VERSION: "If Y is convex in ordered X, then order topology on Y = subspace topology." **)

definition convex_in :: "'a::linorder set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "convex_in X Y \<longleftrightarrow>
     (\<forall>x\<in>Y. \<forall>y\<in>Y. \<forall>z\<in>X. x < z \<and> z < y \<longrightarrow> z \<in> Y)"

theorem Theorem_16_4:
  fixes X :: "'a::linorder set" and Y :: "'a set"
  assumes "convex_in X Y"
  shows "topology_generated_by_basis Y (basis_order_topology \<inter> Pow Y)
       = subspace_topology X order_topology_on_UNIV Y"
  sorry


section \<open>\<S>17 Closed Sets and Limit Points\<close>

subsection \<open>Closed sets\<close>

(** from \S17 Definition (Closed set as complement of open) [top1.tex:~630] **)
definition closedin_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "closedin_on X T A \<longleftrightarrow> A \<subseteq> X \<and> (X - A) \<in> T"

(** de Morgan helper: X - Inter F = Union of (X - A) for A in F **)
lemma diff_Inter_eq: "(X :: 'a set) - \<Inter>F = \<Union>{X - A | A. A \<in> F}"
  apply (rule equalityI)
   apply (rule subsetI)
   apply blast
  apply (rule subsetI)
  apply blast
  done
(** from \S17 Theorem 17.1 [top1.tex:640] **)
(** LATEX VERSION: "Empty and X closed; arbitrary intersections closed; finite unions closed." **)
(** Note: Isabelle's Inter {} = UNIV (not X), so the intersection clause needs F \<noteq> {}. **)
theorem Theorem_17_1:
  assumes hT: "is_topology_on X T"
  shows "closedin_on X T {} \<and> closedin_on X T X
     \<and> (\<forall>F. F \<noteq> {} \<longrightarrow> (\<forall>A\<in>F. closedin_on X T A) \<longrightarrow> closedin_on X T (\<Inter>F))
     \<and> (\<forall>F. finite F \<longrightarrow> (\<forall>A\<in>F. closedin_on X T A) \<longrightarrow> closedin_on X T (\<Union>F))"
  sorry

(** from \S17 Theorem 17.2 [top1.tex:665] **)
(** LATEX VERSION: "A closed in Y iff A = C\<inter>Y for some closed C in X." **)
theorem Theorem_17_2:
  assumes "is_topology_on X T"
  shows "closedin_on Y (subspace_topology X T Y) A \<longleftrightarrow>
     (\<exists>C. closedin_on X T C \<and> A = C \<inter> Y)"
  sorry

(** from \S17 Theorem 17.3 [top1.tex:687] **)
(** LATEX VERSION: "If A closed in Y and Y closed in X then A closed in X." **)
theorem Theorem_17_3:
  assumes hT: "is_topology_on X T"
  assumes hY: "closedin_on X T Y"
  assumes hA: "closedin_on Y (subspace_topology X T Y) A"
  shows "closedin_on X T A"
proof -
  from hY have Y_sub_X: "Y \<subseteq> X" and XmY_T: "X - Y \<in> T"
    unfolding closedin_on_def by blast+
  from hA have A_sub_Y: "A \<subseteq> Y"
    unfolding closedin_on_def by blast
  from hA have YmA_sub: "Y - A \<in> subspace_topology X T Y"
    unfolding closedin_on_def by blast
  from YmA_sub obtain V where hV: "V \<in> T" and hYmA: "Y - A = Y \<inter> V"
    unfolding subspace_topology_def by blast
  from hT have XT: "X \<in> T" and
               inter_T: "\<forall>F. finite F \<and> F \<subseteq> T \<longrightarrow> \<Inter>F \<in> T" and
               union_T: "\<forall>U. U \<subseteq> T \<longrightarrow> \<Union>U \<in> T"
    unfolding is_topology_on_def by blast+
  have XV_T: "X \<inter> V \<in> T"
  proof -
    have "finite {X, V} \<and> {X, V} \<subseteq> T" using XT hV by simp
    then have "\<Inter>{X, V} \<in> T" using inter_T by blast
    then show ?thesis by simp
  qed
  have XmA_eq: "X - A = (X - Y) \<union> (X \<inter> V)"
    using A_sub_Y hYmA by blast
  have XmA_T: "X - A \<in> T"
  proof -
    have "{X - Y, X \<inter> V} \<subseteq> T" using XmY_T XV_T by simp
    then have "\<Union>{X - Y, X \<inter> V} \<in> T" using union_T by blast
    then show ?thesis using XmA_eq by simp
  qed
  show "closedin_on X T A"
    unfolding closedin_on_def using A_sub_Y Y_sub_X XmA_T by blast
qed


subsection \<open>Closure and interior\<close>

(** from \S17 Definition (Interior and closure) [top1.tex:~690] **)
definition interior_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> 'a set" where
  "interior_on X T A = \<Union>{U. U \<in> T \<and> U \<subseteq> A}"

definition closure_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> 'a set" where
  "closure_on X T A = \<Inter>{C. closedin_on X T C \<and> A \<subseteq> C}"

(** from \S17 Theorem 17.4 [top1.tex:703] **)
(** LATEX VERSION: "Closure in Y equals closure in X intersect Y." **)
theorem Theorem_17_4:
  assumes "is_topology_on X T"
  assumes "A \<subseteq> Y" and "Y \<subseteq> X"
  shows "closure_on Y (subspace_topology X T Y) A = closure_on X T A \<inter> Y"
  sorry

(** from \S17 (Terminology: 'A intersects B' iff A\<inter>B \<noteq> {}) [top1.tex:~707] **)
definition intersects :: "'a set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "intersects A B \<longleftrightarrow> A \<inter> B \<noteq> {}"

(** from \S17 Theorem 17.5 [top1.tex:713] **)
(** LATEX VERSION: "x\<in>Cl A iff every open neighborhood intersects A; basis version too." **)
definition neighborhood_of :: "'a \<Rightarrow> 'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "neighborhood_of x X T U \<longleftrightarrow> U \<in> T \<and> x \<in> U"

theorem Theorem_17_5a:
  assumes "is_topology_on X T"
  assumes "x \<in> X" and "A \<subseteq> X"
  shows "x \<in> closure_on X T A \<longleftrightarrow>
    (\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects U A)"
  sorry

theorem Theorem_17_5b:
  assumes "basis_for X B T"
  assumes "x \<in> X" and "A \<subseteq> X"
  shows "x \<in> closure_on X T A \<longleftrightarrow>
    (\<forall>b\<in>B. x \<in> b \<longrightarrow> intersects b A)"
  sorry


subsection \<open>Limit points\<close>

(** from \S17 Definition (Limit point) [top1.tex:~742] **)
definition is_limit_point_of :: "'a \<Rightarrow> 'a set \<Rightarrow> 'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_limit_point_of x A X T \<longleftrightarrow>
     x \<in> X \<and> A \<subseteq> X \<and>
     (\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects (U - {x}) A)"

definition limit_points_of :: "'a set \<Rightarrow> 'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set" where
  "limit_points_of A X T = {x\<in>X. is_limit_point_of x A X T}"

(** from \S17 Theorem 17.6 [top1.tex:751] **)
(** LATEX VERSION: "Cl A = A \<union> A'." **)
theorem Theorem_17_6:
  assumes "is_topology_on X T"
  assumes "A \<subseteq> X"
  shows "closure_on X T A = A \<union> limit_points_of A X T"
  sorry

(** from \S17 Corollary 17.7 [top1.tex:761] **)
(** LATEX VERSION: "A closed iff contains all its limit points." **)
theorem Corollary_17_7:
  assumes "is_topology_on X T"
  assumes "A \<subseteq> X"
  shows "closedin_on X T A \<longleftrightarrow> limit_points_of A X T \<subseteq> A"
  sorry


subsection \<open>Hausdorff spaces, T1 axiom, sequences\<close>

(** from \S17 Definition (Hausdorff space) [top1.tex:780] **)
(** LATEX VERSION: "Distinct points have disjoint neighborhoods." **)
definition is_hausdorff_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_hausdorff_on X T \<longleftrightarrow>
     is_topology_on X T \<and>
     (\<forall>x\<in>X. \<forall>y\<in>X. x \<noteq> y \<longrightarrow>
        (\<exists>U V. neighborhood_of x X T U \<and> neighborhood_of y X T V \<and> U \<inter> V = {}))"

(** from \S17 Theorem 17.8 [top1.tex:782] **)
(** LATEX VERSION: "Every finite point set in Hausdorff space is closed." **)
theorem Theorem_17_8:
  assumes "is_hausdorff_on X T"
  assumes "finite A" and "A \<subseteq> X"
  shows "closedin_on X T A"
  sorry

(** from \S17 (T1 axiom) [top1.tex:~785] **)
definition satisfies_T1_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "satisfies_T1_on X T \<longleftrightarrow> is_topology_on X T \<and> (\<forall>x\<in>X. closedin_on X T {x})"

(** from \S17 Theorem 17.9 [top1.tex:787] **)
(** LATEX VERSION: "In a T1 space, x is limit point of A iff every neighborhood contains infinitely many points of A." **)
theorem Theorem_17_9:
  assumes "satisfies_T1_on X T"
  assumes "A \<subseteq> X" and "x \<in> X"
  shows "is_limit_point_of x A X T \<longleftrightarrow>
    (\<forall>U. neighborhood_of x X T U \<longrightarrow> infinite (U \<inter> A))"
  sorry

(** from \S17 (Definition of sequence convergence) [top1.tex:~770] **)
definition seq_converges_to_on :: "(nat \<Rightarrow> 'a) \<Rightarrow> 'a \<Rightarrow> 'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "seq_converges_to_on s x X T \<longleftrightarrow>
     x \<in> X \<and>
     (\<forall>U. neighborhood_of x X T U \<longrightarrow> (\<exists>N. \<forall>n\<ge>N. s n \<in> U))"

(** from \S17 Theorem 17.10 [top1.tex:801] **)
(** LATEX VERSION: "In Hausdorff space, a sequence converges to at most one point." **)
theorem Theorem_17_10:
  assumes "is_hausdorff_on X T"
  assumes "seq_converges_to_on s x X T"
  assumes "seq_converges_to_on s y X T"
  shows "x = y"
proof (rule ccontr)
  assume neq: "x \<noteq> y"
  from assms(1) have hausdorff: "\<forall>a\<in>X. \<forall>b\<in>X. a \<noteq> b \<longrightarrow>
      (\<exists>U V. neighborhood_of a X T U \<and> neighborhood_of b X T V \<and> U \<inter> V = {})"
    unfolding is_hausdorff_on_def by blast
  from assms(2) have hx: "x \<in> X"
    and conv_x: "\<forall>U. neighborhood_of x X T U \<longrightarrow> (\<exists>N. \<forall>n\<ge>N. s n \<in> U)"
    unfolding seq_converges_to_on_def by blast+
  from assms(3) have hy: "y \<in> X"
    and conv_y: "\<forall>U. neighborhood_of y X T U \<longrightarrow> (\<exists>N. \<forall>n\<ge>N. s n \<in> U)"
    unfolding seq_converges_to_on_def by blast+
  from hausdorff hx hy neq obtain U V where
    hU: "neighborhood_of x X T U" and hV: "neighborhood_of y X T V" and disj: "U \<inter> V = {}"
    by blast
  from conv_x hU obtain N1 where N1: "\<forall>n\<ge>N1. s n \<in> U" by blast
  from conv_y hV obtain N2 where N2: "\<forall>n\<ge>N2. s n \<in> V" by blast
  have "s (max N1 N2) \<in> U \<inter> V"
    using N1[rule_format, of "max N1 N2"] N2[rule_format, of "max N1 N2"] by auto
  with disj show False by simp
qed

(** from \S17 Theorem 17.11 [top1.tex:809] **)
(** LATEX VERSION: "Order topology on simply ordered set is Hausdorff; products/subspaces preserve Hausdorff." **)
theorem Theorem_17_11:
  shows
    "(\<forall>(X::'a::linorder set). is_hausdorff_on X order_topology_on_UNIV)
     \<and> (\<forall>X1 T1 X2 T2.
            is_hausdorff_on X1 T1 \<and> is_hausdorff_on X2 T2 \<longrightarrow>
            is_hausdorff_on (X1 \<times> X2) (product_topology_on T1 T2))
     \<and> (\<forall>X T Y.
            is_hausdorff_on X T \<and> Y \<subseteq> X \<longrightarrow>
            is_hausdorff_on Y (subspace_topology X T Y))"
  sorry

end
